name: Test

on:
  push:
    branches: ['*']
    tags: ['!v*']
  workflow_call: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Test
      run: go test ./...
